"""
config.py - Configuración de constantes y rutas del proyecto.
"""
import os
from pathlib import Path
from dotenv import load_dotenv

_RAIZ = Path(__file__).resolve().parent.parent
load_dotenv(_RAIZ / ".env")

SEED = int(os.getenv("CPYD_SEED", 42))

RUTA_RAIZ = _RAIZ
RUTA_DATA = _RAIZ / "data"
RUTA_OUTPUT = _RAIZ / "output"
RUTA_GRAFICOS = RUTA_OUTPUT / "graficos"
RUTA_RESULTADOS = RUTA_OUTPUT / "resultados.txt"
RUTA_LOG = RUTA_OUTPUT / "log.txt"

RUTA_OUTPUT.mkdir(parents=True, exist_ok=True)
RUTA_GRAFICOS.mkdir(parents=True, exist_ok=True)

CHUNK_SIZE = 50000
N_JOBS = -1
UMBRAL_SHAPIRO = 5000
ALPHA = 0.05
TRAIN_SIZE = 0.70

COL_FECHA = "FECHA"
COL_CANAL = "CANAL"
COL_SKU = "SKU"
COL_PRODUCTO = "PRODUCTO"
COL_UNIDADES = "UNIDADES"
COL_DESCUENTO = "PORCENTAJE DESCUENTO"
COL_MONTO = "MONTO APLICADO"
COL_BOLETA = "BOLETA"
COL_LOCAL = "LOCAL"
COL_CODIGO_CLIENTE = "CODIGO CLIENTE"
COL_RUN_CLIENTE = "RUN CLIENTE"
COL_NOMBRES = "NOMBRES"
COL_APELLIDOS = "APELLIDOS"
COL_FECHA_NACIMIENTO = "FECHA NACIMIENTO"
COL_GENERO = "GENERO"

COL_MONTO_POR_UNIDAD = "MONTO_POR_UNIDAD"
COL_EDAD = "EDAD"
COL_FRECUENCIA_COMPRA = "FRECUENCIA_COMPRA"

COLS_NUMERICAS = [COL_UNIDADES, COL_DESCUENTO, COL_MONTO, COL_MONTO_POR_UNIDAD, COL_EDAD, COL_FRECUENCIA_COMPRA]
COLS_CATEGORICAS = [COL_CANAL, COL_LOCAL, COL_GENERO]
